name: Build and Commit dist/

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Встановлюємо Node.js з corepack
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Node >=16.10 має corepack

      # 3️⃣ Увімкнення corepack + встановлення pnpm
      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.10.5 --activate

      # 4️⃣ Встановлюємо залежності
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5️⃣ Збираємо бібліотеку
      - name: Build UI Kit
        run: pnpm build

      # 6️⃣ Комітимо dist/, якщо є зміни
      - name: Commit and Push dist/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist -f
          if git diff --cached --quiet; then
            echo "✅ No changes in dist/"
          else
            git commit -m "ci: build dist [skip ci]"
            git push origin master
